baseURL: http://example.org/
languageCode: en-au
title: Intro to Hugo
# copyright: Custom Company Name

# menu links via config file
# menu:
#   main:
#   - name: Github
#     url: http://www.github.com
#     weight: 90
#     params:
#       blank: true
#   - name: Google
#     url: http://www.google.com
#     weight: 100
#     params:
#       blank: true

# controls how many items appear on each page when paginating
paginate: 3
# controls the approx word count (rounded to sentences) in a list summary
summaryLength: 30

# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
